[tool.poetry]
name = "seperability"
version = "0.1.3"
description = "Seperability of LLM Capabilities"
authors = ["Nicky Pochinkov"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
repository = "https://github.com/pesvut/seperability"

[tool.poetry.dependencies]
python = "^3.8"
ipykernel = "^6.21.1"
ipywidgets = "^8.0.4"
numpy = "^1.23"
numexpr = "^2.7.0"
torch = "^1.13.0"
tensorboardx = "^2.5.1"
tensorboard = "^2.11.2"
dict-deep = "^4.1.2"
pandas = "^1.5.3"
transformers = "^4.26.0"
datasets = "^2.9.0"
evaluate = "^0.4.0"
zstandard = "^0.19.0"
welford-torch = "^0.1.2"
einops = "^0.6.0"
matplotlib = "^3.6.3"
wandb = "^0.13.9"
accelerate = "^0.16.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
mypy = "^0.991"
autopep8 = "^2.0.1"
sphinx = "^6.1.3"
sphinx-rtd-theme = "^1.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "--import-mode=importlib",
]
