name: Checks

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - '*.md'
      - 'examples/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - '*.md'
      - 'examples/**'

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with dev
      - name: Install pytorch with cuda
        run: poetry run pip install torch
      - name: Pytest
        run: poetry run pytest
        env:
          WANDB_DISABLED: "true"
